version: "3.9"

services:
  db:
    image: postgres:13-alpine
    container_name: db  
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: library
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres    
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      DBPORT: 5432
      DBHOST: db
      DBNAME: library
      DBUSER: postgres
      DBPASSWORD: postgres
    depends_on:
      - db